/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  lifeSidebar: [{type: 'autogenerated', dirName: 'life'}],
  scienceSidebar: [
    {type: 'category',
    label: 'Everyday Science',
    link: {
      type: 'generated-index',
      title: 'Everyday Science',
      slug: '/sci',
      description: 'Short articles about current interests in science'},
    items: [
      {
        type: 'autogenerated',
        dirName: 'science'
      }
    ]
  }
],

  phdSidebar: [
    {type: 'category',
    label: 'My PhD Journey',
    link: {
      type: 'generated-index',
      title: 'My PhD Journey',
      slug: '/phd',
      description: 'This section includes posts about my PhD experiences'},
    items: [
      {
        type: 'autogenerated',
        dirName: 'phd'
      }
    ]
  }
],
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
